CREATE TABLE CUSTOMER (
    CUSTNO VARCHAR(8) NOT NULL,
    CUSTNAME VARCHAR(30) NOT NULL,
    ADDRESS VARCHAR(50) NOT NULL,
    INTERNAL CHAR(1) NOT NULL,
    CONTACT VARCHAR(35) NOT NULL,
    PHONE VARCHAR(11) NOT NULL,
    CITY VARCHAR(30) NOT NULL,
    STATE VARCHAR(2) NOT NULL,
    ZIP VARCHAR(10) NOT NULL,
    CONSTRAINT PK_CUSTOMER PRIMARY KEY (CUSTNO)
);

CREATE TABLE FACILITY (
    FACNO VARCHAR(8) NOT NULL,
    FACNAME VARCHAR(30) NOT NULL,
    CONSTRAINT PK_FACILITY PRIMARY KEY (FACNO)
);

CREATE TABLE LOCATION(
	LOCNO VARCHAR(8) NOT NULL,
	FACNO VARCHAR(8) NOT NULL,
    LOCNAME VARCHAR(30) NOT NULL,
    CONSTRAINT PK_LOCATION PRIMARY KEY (LOCNO),
    CONSTRAINT FK_LOC_FACNO FOREIGN KEY (FACNO) 
		REFERENCES FACILITY (FACNO)
    );

CREATE TABLE EMPLOYEE (
    EMPNO VARCHAR(8) NOT NULL,
    EMPNAME VARCHAR(30) NOT NULL,
    DEPARTMENT VARCHAR(20) NOT NULL,
    EMAIL VARCHAR(30) NOT NULL,
    PHONE VARCHAR(11) NOT NULL,
    CONSTRAINT PK_EMPLOYEE PRIMARY KEY (EMPNO)
);
    
CREATE TABLE RESOURCETBL (
    RESNO VARCHAR(8) NOT NULL,
    RESNAME VARCHAR(30) NOT NULL,
    RATE FLOAT(2) NOT NULL CHECK( RATE > 0),
    CONSTRAINT PK_RESOURCETBL PRIMARY KEY (RESNO)
);

CREATE TABLE EVENTREQUEST(
	EVENTNO VARCHAR(8) NOT NULL,
    DATEHELD DATE NOT NULL,
    DATEREQ DATE NOT NULL,
    CUSTNO VARCHAR(8) NOT NULL,
    FACNO VARCHAR(8) NOT NULL,
    DATEAUTH DATE,
    STATUS VARCHAR(10) NOT NULL CHECK( STATUS IN('Pending', 'Denied', 'Approved')),
    ESTCOST FLOAT NOT NULL,
    ESTAUDIENCE INTEGER NOT NULL CHECK( ESTAUDIENCE > 0),
    BUDNO VARCHAR(8),
    CONSTRAINT PK_EVENTREQUEST PRIMARY KEY (EVENTNO),
    CONSTRAINT FK_EVTREQ_CUSTNO FOREIGN KEY (CUSTNO) 
		REFERENCES CUSTOMER (CUSTNO),
	CONSTRAINT FK_EVTREQ_FACNO FOREIGN KEY (FACNO)
		REFERENCES FACILITY (FACNO)
);

CREATE TABLE EVENTPLAN(
	PLANNO VARCHAR(8) NOT NULL,
    EVENTNO VARCHAR(8) NOT NULL,
    WORKDATE DATE NOT NULL,
    NOTES VARCHAR(50),
    ACTIVITY VARCHAR(20) NOT NULL,
    EMPNO VARCHAR(8),
    CONSTRAINT PK_EVENTPLAN PRIMARY KEY (PLANNO),
    CONSTRAINT FK_EVTPLN_EVENTNO FOREIGN KEY (EVENTNO)
		REFERENCES EVENTREQUEST(EVENTNO),
	CONSTRAINT FK_EVTPLN_EMPNO FOREIGN KEY (EMPNO)
		REFERENCES EMPLOYEE(EMPNO)
);

CREATE TABLE EVENTPLANLINE(
	PLANNO VARCHAR(8) NOT NULL,
    LINENO VARCHAR(8) NOT NULL,
    TIMESTART DATETIME NOT NULL,
    TIMEEND DATETIME NOT NULL,
	NUMBERFLD INTEGER NOT NULL,
    LOCNO VARCHAR(8) NOT NULL,
    RESNO VARCHAR(8) NOT NULL,
    CONSTRAINT PK_EVENTPLANLINE PRIMARY KEY (PLANNO, LINENO),
    CONSTRAINT FK_PLANNO FOREIGN KEY (PLANNO)
		REFERENCES EVENTPLAN (PLANNO),
	CONSTRAINT FK_EVTPLNL_LOCNO FOREIGN KEY (LOCNO)
		REFERENCES LOCATION (LOCNO),
	CONSTRAINT FK_EVTPLNL_RESNO FOREIGN KEY (RESNO)
		REFERENCES RESOURCETBL (RESNO),
	CHECK (TIMESTART < TIMEEND)
);

